<center><h1>NumPy Problems</h1></center>

<left><h3>Importing the NumPy</h3></left>

In [146]:
import numpy as np

1. Write a Python program to convert a list of numeric value into a one-dimensional
NumPy array.<br>
Expected Output:<br>
Original List: [12.23, 13.32, 100, 36.32]<br>
One-dimensional numpy array: [ 12.23 13.32 100. 36.32]

In [147]:
array_one=[12.23,13.32,100,36.32]
array_two=np.array(array_one)
print(f"Original list: {array_one}")
print(f"One-dimensional numpy array: {array_two}")

Original list: [12.23, 13.32, 100, 36.32]
One-dimensional numpy array: [ 12.23  13.32 100.    36.32]


2. Create a 3x3 matrix with values ranging from 2 to 10.
<br>Expected Output:<br>
[[ 2 3 4]<br>
[ 5 6 7]<br>
[ 8 9 10]]<br>

In [148]:
num_list=[]
for counter in range(2,11):
    num_list.append(counter)

num_array=np.array(num_list)
array_3D=num_array.reshape(3,3)
print(array_3D)

[[ 2  3  4]
 [ 5  6  7]
 [ 8  9 10]]


3. Write a Python program to create a null vector of size 10 and update sixth value to 11.<br>
[ 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]<br>
Update sixth value to 11<br>
[ 0. 0. 0. 0. 0. 0. 11. 0. 0. 0.]

In [149]:
num_list=[]
for i in range(10):
    num_list.append(0)

num_array=np.array(num_list)
print(f"Before Updation\n{num_array}")
num_array[-4]=11
print(f"After Updation\n{num_array}")

Before Updation
[0 0 0 0 0 0 0 0 0 0]
After Updation
[ 0  0  0  0  0  0 11  0  0  0]


4. Write a Python program to reverse an array (first element becomes last).<br>
Original array:<br>
[12 13 14 15 16 17 18 19 20 21 22 23 24 25 26 27 28 29 30 31 32 33 34 35 36 37]<br>
Reverse array:<br>
[37 36 35 34 33 32 31 30 29 28 27 26 25 24 23 22 21 20 19 18 17 16 15 14 13 12]

In [150]:
num_array=np.array([12,13,14,15,16,17,18,19,20,21,22,23,24,25,26,27,28,29,30,31,32,33,34,35,36,37])
reverse_array=num_array[::-1]
print(f"original array:\n{num_array}")
print(f"Reverse array:\n{reverse_array}")

original array:
[12 13 14 15 16 17 18 19 20 21 22 23 24 25 26 27 28 29 30 31 32 33 34 35
 36 37]
Reverse array:
[37 36 35 34 33 32 31 30 29 28 27 26 25 24 23 22 21 20 19 18 17 16 15 14
 13 12]


5. Write a Python program to create a 2d array with 1 on the border and 0 inside.<br>
Expected Output:<br>
Original array:<br>
[[ 1. 1. 1. 1. 1.]<br>
[ 1. 1. 1. 1. 1.]<br>
[ 1. 1. 1. 1. 1.]<br>
[ 1. 1. 1. 1. 1.]<br>
[ 1. 1. 1. 1. 1.]]<br>
1 on the border and 0 inside in the array<br>
[[ 1. 1. 1. 1. 1.]<br>
[ 1. 0. 0. 0. 1.]<br>
[ 1. 0. 0. 0. 1.]<br>
[ 1. 0. 0. 0. 1.]<br>
[ 1. 1. 1. 1. 1.]]<br>

In [151]:
num_list=[1 for counter in range(25)]
num_array=np.array(num_list)
num_array=num_array.reshape(5,5)
print(f"Original array:\n{num_array}\n")

new_array=np.copy(num_array)
for counter1 in range(5):
    for counter2 in range(5):
        if counter1 in [1,2,3] and counter2 in [1,2,3]:
            new_array[counter1][counter2]=0

print(new_array)

Original array:
[[1 1 1 1 1]
 [1 1 1 1 1]
 [1 1 1 1 1]
 [1 1 1 1 1]
 [1 1 1 1 1]]

[[1 1 1 1 1]
 [1 0 0 0 1]
 [1 0 0 0 1]
 [1 0 0 0 1]
 [1 1 1 1 1]]


6. Write a Python program to add a border (filled with 0's) around an existing array.<br>
Expected Output:<br>
Original array:<br>
[[ 1. 1. 1.]<br>
[ 1. 1. 1.]<br>
[ 1. 1. 1.]]<br>
1 on the border and 0 inside in the array<br>
[[ 0. 0. 0. 0. 0.]<br>
[ 0. 1. 1. 1. 0.]<br>
[ 0. 1. 1. 1. 0.]<br>
[ 0. 1. 1. 1. 0.]<br>
[ 0. 0. 0. 0. 0.]]<br>

In [152]:
num_list=[1 for i in range(9)]
num_array=np.array(num_list)
num_array=num_array.reshape(3,3)
print(f"Original array:\n{num_array}\n")

new_array=np.zeros((5,5))
for i in range(5):
    for j in range(5):
        if i in [1,2,3] and j in [1,2,3]:
            new_array[i][j]=1

print(new_array)


Original array:
[[1 1 1]
 [1 1 1]
 [1 1 1]]

[[0. 0. 0. 0. 0.]
 [0. 1. 1. 1. 0.]
 [0. 1. 1. 1. 0.]
 [0. 1. 1. 1. 0.]
 [0. 0. 0. 0. 0.]]


7. Write a Python program to create a 8x8 matrix and fill it with a checkerboard pattern.<br>
Checkerboard pattern:<br>
[[0 1 0 1 0 1 0 1]<br>
[1 0 1 0 1 0 1 0]<br>
[0 1 0 1 0 1 0 1]<br>
[1 0 1 0 1 0 1 0]<br>
[0 1 0 1 0 1 0 1]<br>
[1 0 1 0 1 0 1 0]<br>
[0 1 0 1 0 1 0 1]<br>
[1 0 1 0 1 0 1 0]]<br>

In [153]:
num_list1=[0 if i%2==0 else 1 for i in range(8)]
num_list2=[1 if i%2==0 else 0 for i in range(8)]
num_list3=[]
for i in range(8):
    if i%2==0:
        num_list3+=num_list1
    else:
        num_list3+=num_list2

num_array=np.array(num_list3)
num_array=num_array.reshape(8,8)
print(num_array)

[[0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]]


8. Write a Python program to convert a list and tuple into arrays.<br>
List to array:<br>
[1 2 3 4 5 6 7 8]<br>
Tuple to array:<br>
[[8 4 6]<br>
[1 2 3]]

In [154]:
num_list=[1,2,3,4,5,6,7,8]
num_tuple=(1,2,3,4,5,6,7,8)
num_array_list=np.array(num_list)
num_array_tuple=np.array(num_tuple)
print(f"List to array:\n{num_array_list}")
print(f"tuple to array:\n{num_array_tuple}")

List to array:
[1 2 3 4 5 6 7 8]
tuple to array:
[1 2 3 4 5 6 7 8]


9. Write a Python program to append values to the end of an array.<br>
Expected Output:<br>
Original array:<br>
[10, 20, 30]<br>
After append values to the end of the array:<br>
[10 20 30 40 50 60 70 80 90]

In [155]:
num_array=np.array([10,20,30])
print(f"Original array:\n{num_array}")
num_array=np.append(num_array,40)
num_array=np.append(num_array,50)
num_array=np.append(num_array,60)
num_array=np.append(num_array,70)
num_array=np.append(num_array,80)
num_array=np.append(num_array,90)
print(f"After append values to the end of the array:\n{num_array}")


Original array:
[10 20 30]
After append values to the end of the array:
[10 20 30 40 50 60 70 80 90]


10. Write a Python program to find the real and imaginary parts of an array of complex
numbers.<br>
Expected Output:<br>
Original array [ 1.00000000+0.j 0.70710678+0.70710678j]<br>
Real part of the array:<br>
[ 1. 0.70710678]<br>
Imaginary part of the array:<br>
[ 0. 0.70710678]

In [156]:
num_array=np.array([1.00000000+0.j,0.70710678+0.70710678j])
real_part=num_array.real
imag_part=num_array.imag
print(f"Original array {num_array}")
print(f"Real part of the array:\n{real_part}\nImaginary part of the array:\n{imag_part}")

Original array [1.        +0.j         0.70710678+0.70710678j]
Real part of the array:
[1.         0.70710678]
Imaginary part of the array:
[0.         0.70710678]


11. Write a Python program to find the number of elements of an array, length of one<br>
array element in bytes and total bytes consumed by the elements.<br>
Expected Output:<br>
Size of the array: 3<br>
Length of one array element in bytes: 8<br>
Total bytes consumed by the elements of the array: 24

In [157]:
num_array=np.array([[1,2,3,4,5,6,7,8],[9,10,11,12,13,14,15,16],[17,18,19,20,21,22,23,24]])
num=0
total_size=0
for i in num_array:
    num+=1
    size_one=i.size
    total_size+=i.size

print(f"Size of the array: {num}")
print(f"Length of one array element: {size_one}")
print(f"Total bytes consumed by the elements of the array: {total_size}")

Size of the array: 3
Length of one array element: 8
Total bytes consumed by the elements of the array: 24


12. Write a Python program to find common values between two arrays.<br>
Expected Output:<br>
Array1: [ 0 10 20 40 60]<br>
Array2: [10, 30, 40]<br>
Common values between two arrays:<br>
[10 40]

In [158]:
num_array1=np.array([0,10,20,40,60])
num_array2=np.array([10,30,40])

num_array3=np.intersect1d(num_array1,num_array2)
print(f"Array1: {num_array1}")
print(f"Array2: {num_array2}")
print(f"Common values between two arrays:\n{num_array3}")

Array1: [ 0 10 20 40 60]
Array2: [10 30 40]
Common values between two arrays:
[10 40]


13. Write a Python program to find the set difference of two arrays. The set difference
will return the sorted, unique values in array1 that are not in array2.<br>
Expected Output:<br>
Array1: [ 0 10 20 40 60 80]<br>
Array2: [10, 30, 40, 50, 70, 90]<br>
Set difference between two arrays:<br>
[ 0 20 60 80]

In [159]:
num_array1=np.array([0,10,20,40,60,80])
num_array2=np.array([10,30,40,50,70,90])

num_array3=np.setdiff1d(num_array1,num_array2)
print(f"Array1: {num_array1}")
print(f"Array2: {num_array2}")
print(f"Set difference between two arrays:\n{num_array3}")

Array1: [ 0 10 20 40 60 80]
Array2: [10 30 40 50 70 90]
Set difference between two arrays:
[ 0 20 60 80]


14. Write a Python program to find the set exclusive-or of two arrays. Set exclusive-or<br>
will return the sorted, unique values that are in only one (not both) of the input arrays.<br>
Array1: [ 0 10 20 40 60 80]<br>
Array2: [10, 30, 40, 50, 70]<br>
Unique values that are in only one (not both) of the input arrays:<br>
[ 0 20 30 50 60 70 80]

In [160]:
num_array1=np.array([0,10,20,40,60,80])
num_array2=np.array([10,30,40,50,70])

num_array3=np.setxor1d(num_array1,num_array2)
print(f"Array1: {num_array1}")
print(f"Array2: {num_array2}")
print(f"Unique values that are in only one (not both) of the input arrays:\n{num_array3}")

Array1: [ 0 10 20 40 60 80]
Array2: [10 30 40 50 70]
Unique values that are in only one (not both) of the input arrays:
[ 0 20 30 50 60 70 80]


15. Write a Python program compare two arrays using numpy.<br>
Array a: [1 2]<br>
Array b: [4 5]<br>
a > b<br>
[False False]<br>
a >= b<br>
[False False]<br>
a < b<br>
[ True True]<br>
a <= b<br>
[ True True]

In [161]:
num_array1=np.array([1,2])
num_array2=np.array([4,5])
print(f"Array a: {num_array1}")
print(f"Array b: {num_array2}")
print(f"a > b\n{num_array1>num_array2}")
print(f"a >= b\n{num_array1>=num_array2}")
print(f"a < b\n{num_array1<num_array2}")
print(f"a <= b\n{num_array1<=num_array2}")

Array a: [1 2]
Array b: [4 5]
a > b
[False False]
a >= b
[False False]
a < b
[ True  True]
a <= b
[ True  True]


15. Write a Python program to save a NumPy array to a text file.

In [162]:
def write_to_file(num_array):
    with open("sample.txt","a") as file:
        file.write(f"The array is : {num_array}")

num_array=np.array([1,2,3,4,5])
write_to_file(num_array)

16. Write a Python program to create a contiguous flattened array.<br>
Original array:<br>
[[10 20 30]<br>
[20 40 50]]<br>
New flattened array:<br>
[10 20 30 20 40 50]

In [163]:
num_array=np.array([[10,20,30],[20,40,50]])
print(f"Original array:\n{num_array}")
num_array=num_array.reshape(num_array.size)
print(f"New flattened array:\n{num_array}")

Original array:
[[10 20 30]
 [20 40 50]]
New flattened array:
[10 20 30 20 40 50]


17. Write a Python program to change the data type of an array.<br>
Expected Output:<br>
[[ 2 4 6]<br>
[ 6 8 10]]<br>
Data type of the array x is: int32<br>
New Type: float64<br>
[[ 2. 4. 6.]<br>
[ 6. 8. 10.]]

In [164]:
num_array=np.array([[2,4,6],[6,8,10]])
print(num_array)
print(f"Data type of the array x is: {num_array.dtype}")
num_array=num_array.astype("f")
print(f"Data type of the array x is: {num_array.dtype}")
print(num_array)

[[ 2  4  6]
 [ 6  8 10]]
Data type of the array x is: int32
Data type of the array x is: float32
[[ 2.  4.  6.]
 [ 6.  8. 10.]]


18. Write a Python program to create a 3-D array with ones on a diagonal and zeros
elsewhere.<br>
Expected Output:<br>
[[ 1. 0. 0.]<br>
[ 0. 1. 0.]<br>
[ 0. 0. 1.]]

In [165]:
num_array=np.zeros((3,3))
for i in range(3):
    for j in range(3):
        if (i,j) in [(0,0),(1,1),(2,2)]:
            num_array[i][j]=1

print(num_array)

[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]


19. Write a Python program to create an array which looks like below array.<br>
Expected Output:<br>
[[ 0. 0. 0.]<br>
[ 1. 0. 0.]<br>
[ 1. 1. 0.]<br>
[ 1. 1. 1.]]

In [166]:
num_array=np.zeros((4,3))
for i in range(4):
    num_array[i,:i]=1

print(num_array)

[[0. 0. 0.]
 [1. 0. 0.]
 [1. 1. 0.]
 [1. 1. 1.]]


20. Write a Python program to concatenate two 2-dimensional arrays.<br>
Expected Output:<br>
Sample arrays: ([[0, 1, 3], [5, 7, 9]], [[0, 2, 4], [6, 8, 10]]<br>
Expected Output:<br>
[[ 0 1 3 0 2 4]<br>
[ 5 7 9 6 8 10]]

In [167]:
num_array=np.array([[[0, 1, 3], [5, 7, 9]], [[0, 2, 4], [6, 8, 10]]])
final_array=np.concatenate((num_array[0],num_array[1]),axis=1)
print(final_array)

[[ 0  1  3  0  2  4]
 [ 5  7  9  6  8 10]]


21. Write a Python program to make an array immutable (read-only).<br>
Expected Output:<br>
Test the array is read-only or not:<br>
Try to change the value of the first element:<br>
Traceback (most recent call last):<br>
File "19236bd0-0bd9-11e7-a232-c706d0968eb6.py", line 6, in<br>
x[0] = 1<br>
ValueError: assignment destination is read-only

In [168]:
num_array=np.array([1,2,3,4])
num_array.flags.writeable=False
print("Test the array is read-only or not:")
print("Try to change the value of the first element:")
"""
num_array[0]=10
print(num_array)
The Above code results in error as we have given num_array writeable flag as False
"""
try:
    num_array[0]=1

except ValueError as ve:
    print(f"ValueError: {ve}")


Test the array is read-only or not:
Try to change the value of the first element:
ValueError: assignment destination is read-only


22. Write a Python program to create an array of (3, 4) shape, multiply every element
value by 3 and display the new array.<br>
Expected Output:<br>
Original array elements:<br>
[[ 0 1 2 3]<br>
[ 4 5 6 7]<br>
[ 8 9 10 11]]<br>
New array elements:<br>
[[ 0 3 6 9]<br>
[12 15 18 21]<br>
[24 27 30 33]]

In [169]:
num_array=np.arange(0,12)
num_array=num_array.reshape(3,4)
print(f"Original array elements:\n{num_array}")
num_array=np.multiply(num_array,3)
print(f"New array elements:\n{num_array}")

Original array elements:
[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]]
New array elements:
[[ 0  3  6  9]
 [12 15 18 21]
 [24 27 30 33]]


23. Write a Python program to convert a NumPy array into Python list structure.
Expected Output:<br>
Original array elements:<br>
[[0 1]<br>
[2 3]<br>
[4 5]]<br>
Array to list:<br>
[[0, 1], [2, 3], [4, 5]]

In [170]:
num_array=np.array([0,1,2,3,4,5])
num_array=num_array.reshape(3,2)
print(f"Original array elements:\n{num_array}")
num_array=num_array.tolist()
print(f"Array to list:\n{num_array}")

Original array elements:
[[0 1]
 [2 3]
 [4 5]]
Array to list:
[[0, 1], [2, 3], [4, 5]]


24. Write a Python program to convert a NumPy array into Python list structure.
Expected Output:<br>
Original array elements:<br>
[ 0.26153123 0.52760141 0.5718299 0.5927067 0.7831874 0.69746349<br>
0.35399976 0.99469633 0.0694458 0.54711478]<br>
Print array values with precision 3:<br>
[ 0.262 0.528 0.572 0.593 0.783 0.697 0.354 0.995 0.069 0.547]

In [171]:
float_array=np.array([0.26153123,0.52760141,0.5718299,0.5927067,0.7831874,0.69746349,0.35399976,0.99469633,0.0694458,0.54711478])
print(f"Original array elements:\n{float_array}")
float_array=np.round(float_array,decimals=3)
float_array=float_array.tolist()
print(f"Print array values with precision 3:\n{float_array}")

Original array elements:
[0.26153123 0.52760141 0.5718299  0.5927067  0.7831874  0.69746349
 0.35399976 0.99469633 0.0694458  0.54711478]
Print array values with precision 3:
[0.262, 0.528, 0.572, 0.593, 0.783, 0.697, 0.354, 0.995, 0.069, 0.547]


25. Write a Python program to suppresses the use of scientific notation for small
numbers in numpy array.<br>
Expected Output:<br>
Original array elements:<br>
[ 1.60000000e-10 1.60000000e+00 1.20000000e+03 2.35000000e-01]<br>
Print array values with precision 3:<br>
[ 0. 1.6 1200. 0.235]

In [172]:
float_array=np.array([1.60000000e-10,1.60000000e+00,1.20000000e+03,2.35000000e-01])
print(f"Original array elements:\n{float_array}")
np.set_printoptions(suppress=True)
np.round(float_array,decimals=1)
print(f"Print array values with precision 3:\n{float_array}")

Original array elements:
[   0.       1.6   1200.       0.235]
Print array values with precision 3:
[   0.       1.6   1200.       0.235]


26. Write a Python program to how to add an extra column to an numpy array.<br>
Expected Output:<br>
[[ 10 20 30 100]<br>
[ 40 50 60 200]]

In [173]:
num_array1=np.array([[10,20,30],[40,50,60]])
num_array2=np.array([[100],[200]])
num_array=np.hstack((num_array1,num_array2))
print(num_array)

[[ 10  20  30 100]
 [ 40  50  60 200]]


27. Write a Python program to remove specific elements in a numpy array.<br>
Expected Output:<br>
Original array:<br>
[ 10 20 30 40 50 60 70 80 90 100]<br>
Delete first, fourth and fifth elements:<br>
[ 20 30 60 70 80 90 100]

In [174]:
num_array=np.array([10,20,30,40,50,60,70,80,90,100])
print(f"Original list:\n{num_array}")
num_array=np.delete(num_array,0)
num_array=np.delete(num_array,2)
num_array=np.delete(num_array,2)
print(f"Delete first, fourth and fifth elements:\n{num_array}")

Original list:
[ 10  20  30  40  50  60  70  80  90 100]
Delete first, fourth and fifth elements:
[ 20  30  60  70  80  90 100]
